#!/bin/bash

# Creating config directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
# mkdir -p "$XDG_CONFIG_HOME"/nixpkgs
echo "Creating config directories"

# Install nix packages

# ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix
# echo "Linking config.nix"

# Install Nix packages from config.nix
# nix-env -iA nixpkgs.myPackages
# echo "Installing Nix packages"

# Ubuntu packages
sudo apt update
sudo apt install tmux zsh

# Starship Installing
curl -sS https://starship.rs/install.sh | sh
# brew option
# brew install starship neovim tmux

# Install Oh my zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting

# linking config
# ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -s "$PWD/nvim" "$XDG_CONFIG_HOME/"
echo "Linking nvim"
ln -sf "$PWD/.zshrc" "$HOME"/.zshrc
echo "Linking .zshrc"
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
echo "Linking tmux"
